apiVersion: v1
kind: Namespace
metadata:
  name: cicd
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus-data
  namespace: cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: cicd
  labels:
    app: nexus
spec:
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      initContainers:
      - name: init
        image: busybox:latest
        command: ['/bin/chown', '200:200', '/nexus-data']
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
      containers:
      - image: sonatype/nexus3:3.27.0
        name: nexus
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
        ports:
        - containerPort: 8081
        - containerPort: 8086
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 5
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-data
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: cicd
spec:
  type: LoadBalancer
  selector:
    app: nexus
  ports:
    - name: ui
      protocol: TCP
      port: 80
      targetPort: 8081
    - name: registry
      protocol: TCP
      port: 8086
      targetPort: 8086

